# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 06:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="El numero tiene que tener este formato '55-5555-5555'.", regex='^\\+?1?\\d{10,15}$')])),
                ('opening', models.TimeField(verbose_name='apertura')),
                ('closing', models.TimeField(verbose_name='clausura')),
                ('lat', models.CharField(blank=True, max_length=500, verbose_name='latitud')),
                ('lon', models.CharField(blank=True, max_length=500, verbose_name='longitud')),
            ],
            options={
                'verbose_name_plural': 'Negocios',
                'verbose_name': 'Negocio',
            },
        ),
    ]
